"""add a category:111 for test

Revision ID: 00880842cc5f
Revises: d19daf0bd663
Create Date: 2016-08-19 02:06:33.567869

"""

# revision identifiers, used by Alembic.
revision = '00880842cc5f'
down_revision = 'd19daf0bd663'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
