"""just test

Revision ID: a19ddd45973d
Revises: 00880842cc5f
Create Date: 2016-08-19 02:33:30.903375

"""

# revision identifiers, used by Alembic.
revision = 'a19ddd45973d'
down_revision = '00880842cc5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
