"""add a category:000 for test

Revision ID: d19daf0bd663
Revises: 4279477026b7
Create Date: 2016-08-19 01:49:37.045727

"""

# revision identifiers, used by Alembic.
revision = 'd19daf0bd663'
down_revision = '4279477026b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
