"""initial migration

Revision ID: eaf3cf5e5f6f
Revises: None
Create Date: 2016-08-15 01:26:04.413808

"""

# revision identifiers, used by Alembic.
revision = 'eaf3cf5e5f6f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
